### PR TITLE
TRT-1125: Support over all risk reasons and escape html in links

### PR DESCRIPTION
**Pull request by neisw**
Addresses issues in [TRT-1167](https://issues.redhat.com/browse/TRT-1167?focusedId=22736351&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22736351) regarding missing global test failure reasons and invalid html link characters

Example after update:

Job Failure Risk Analysis for sha: e2cad6663c9186b487ec56daf33c671e69e09475

| Job Name | Failure Risk |
|:---|:---|
|[pull-ci-openshift-origin-master-e2e-openstack-ovn](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28120/pull-ci-openshift-origin-master-e2e-openstack-ovn/1686778922848489472)|**High**<br>28 tests failed in this run: High|
|[pull-ci-openshift-origin-master-e2e-gcp-ovn](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28120/pull-ci-openshift-origin-master-e2e-gcp-ovn/1686778918683545600)|**Medium**<br>*[sig-instrumentation] Prometheus [apigroup:image.openshift.io] when installed on the cluster should report telemetry [Late] [Skipped:Disconnected] [Suite:openshift/conformance/parallel]*<br>This test has passed 94.59% of 37 runs on jobs ['periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn'] in the last 14 days.<br><br>Open Bugs<br>[Prometheus reporting telemetry test intermittent failures due to server side rate limiting](https://issues.redhat.com/browse/OCPBUGS-16615)|
|[pull-ci-openshift-origin-master-e2e-aws-ovn-serial](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28120/pull-ci-openshift-origin-master-e2e-aws-ovn-serial/1686778918226366464)|**Medium**<br>*[sig-arch] events should not repeat pathologically*<br>This test has passed 96.00% of 50 runs on jobs ['periodic-ci-openshift-release-master-ci-4.14-e2e-aws-ovn-serial' 'periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-serial'] in the last 14 days.<br><br>Open Bugs<br>[Excessive TopologyAwareHintsDisabled events due to service/dns-default with topology aware hints activated.](https://issues.redhat.com/browse/OCPBUGS-11449)<br>[Pathological test failing on reason/FailedMount in openshift-monitoring](https://issues.redhat.com/browse/OCPBUGS-15192)<br>[DNS operator prone to spamming TopologyAwareHintsDisable events on GCP/Azure since May 5](https://issues.redhat.com/browse/OCPBUGS-13366)<br>[CI fails on &#34;events should not repeat pathologically&#34;, reason &#34;FailedAttachVolume&#34;](https://issues.redhat.com/browse/OCPBUGS-14400)<br>[Excessive TopologyAwareHintsDisabled events due to service/dns-default with topology aware hints activated.](https://issues.redhat.com/browse/OCPBUGS-5943)<br>[Fix [TRT-596](https://issues.redhat.com//browse/TRT-596) in master (4.13)](https://issues.redhat.com/browse/OCPBUGS-3640)|
|[pull-ci-openshift-origin-master-e2e-aws-ovn-single-node-serial](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28120/pull-ci-openshift-origin-master-e2e-aws-ovn-single-node-serial/1686778918368972800)|**Low**<br>*[sig-arch][Late] operators should not create watch channels very often [apigroup:apiserver.openshift.io] [Suite:openshift/conformance/parallel]*<br>This test has passed 77.78% of 36 runs on jobs ['periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial'] in the last 14 days.<br>---<br>*[sig-network-edge] ns/openshift-authentication route/oauth-openshift disruption/ingress-to-oauth-server connection/reused should be available throughout the test*<br>This test has passed 30.56% of 36 runs on jobs ['periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial'] in the last 14 days.<br>---<br>*[sig-network-edge] ns/openshift-console route/console disruption/ingress-to-console connection/new should be available throughout the test*<br>This test has passed 27.78% of 36 runs on jobs ['periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial'] in the last 14 days.<br>---<br>*[sig-network-edge] ns/openshift-console route/console disruption/ingress-to-console connection/reused should be available throughout the test*<br>This test has passed 27.78% of 36 runs on jobs ['periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial'] in the last 14 days.<br>---<br>Showing 4 of 5 test results|

### CODE REVIEW

**Comment by stbenjam** [comment]
TRT-1125

**Comment by stbenjam** [comment]
[Fix TRT-596 in master (4.13)](https://issues.redhat.com/browse/OCPBUGS-3640)

**Comment by neisw** [comment]
[TRT&#45;1125](https://issues.redhat.com//browse/TRT-1125)

Test html escape `& # 45;`

**Comment by neisw** [comment]
[Fix TRT&#45;596 in master (4.13)](https://issues.redhat.com/browse/OCPBUGS-3640) test escaping

**Pull request merged**
