### PR TITLE
add top level indicator for infra, install, upgrade

### PR DESCRIPTION
**Pull request by deads2k**
Screenshot from 2020-09-22 09-39-45

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k give me a heading(preferably w/ mouse-over text explaining the categories)+some separation between the TOC and the top level indicator and lgtm.

**Comment by bparees** [comment]
> How do I do that?

the same way the other tables do, you should be able to copy from them.

**Comment by deads2k** [comment]
> > How do I do that?
> 
> the same way the other tables do, you should be able to copy from them.

Oh, this is the `<th>` thing?

**Pull request merged**
