### PR TITLE
test suite nurp

### PR DESCRIPTION
**Pull request by dgoodwin**
- Revert "Revert "Differentiate on test suite in NURPs test tables.""
- Add left join for suites to fix bug.

### CODE REVIEW

**Comment by dgoodwin** [comment]
I think your suggestion looks right @stbenjam , the left join fixes the indicators, test tables look correct as far as I can see across 100k+ rows.

**Comment by stbenjam** [comment]
I'll unhold before I leave today, rebuilding the matview takes a while.

**Pull request merged**
