### PR TITLE
trt-1666: Add view to show existing triaged incidents

### PR DESCRIPTION
**Pull request by neisw**
Adds a new `Triaged Incidents` tab to the RegressedTests modal dialog

Sample [localhost 4.16  6/7 - 6/14](http://localhost:3000/sippy-ng/component_readiness/main?baseEndTime=2024-06-27%2023%3A59%3A59&baseRelease=4.16&baseStartTime=2024-05-31%2000%3A00%3A00&columnGroupBy=Platform&columnGroupBy=Architecture&columnGroupBy=Network&confidence=95&ignoreDisruption=1&ignoreMissing=0&includeVariant=Architecture%3Aamd64&includeVariant=FeatureSet%3Adefault&includeVariant=Installer%3Aipi&includeVariant=Installer%3Aupi&includeVariant=Owner%3Aeng&includeVariant=Platform%3Aaws&includeVariant=Platform%3Aazure&includeVariant=Platform%3Agcp&includeVariant=Platform%3Ametal&includeVariant=Platform%3Avsphere&includeVariant=Topology%3Aha&minFail=3&pity=5&regressedModal=1&sampleEndTime=2024-08-14%2023%3A59%3A59&samplePRNumber=&samplePROrg=&samplePRRepo=&sampleRelease=4.17&sampleStartTime=2024-08-08%2000%3A00%3A00)

Sample [localhost 4.17 8/8 - 8/14](http://localhost:3000/sippy-ng/component_readiness/main?baseEndTime=2024-06-27%2023%3A59%3A59&baseRelease=4.16&baseStartTime=2024-05-31%2000%3A00%3A00&columnGroupBy=Platform&columnGroupBy=Architecture&columnGroupBy=Network&confidence=95&ignoreDisruption=1&ignoreMissing=0&includeVariant=Architecture%3Aamd64&includeVariant=FeatureSet%3Adefault&includeVariant=Installer%3Aipi&includeVariant=Installer%3Aupi&includeVariant=Owner%3Aeng&includeVariant=Platform%3Aaws&includeVariant=Platform%3Aazure&includeVariant=Platform%3Agcp&includeVariant=Platform%3Ametal&includeVariant=Platform%3Avsphere&includeVariant=Topology%3Aha&minFail=3&pity=5&regressedModal=1&sampleEndTime=2024-08-14%2023%3A59%3A59&samplePRNumber=&samplePROrg=&samplePRRepo=&sampleRelease=4.17&sampleStartTime=2024-08-08%2000%3A00%3A00)

Sample [localhost 4.17 7/26 - 8/2](http://localhost:3000/sippy-ng/component_readiness/main?baseEndTime=2024-06-27%2023%3A59%3A59&baseRelease=4.16&baseStartTime=2024-05-31%2000%3A00%3A00&columnGroupBy=Platform&columnGroupBy=Architecture&columnGroupBy=Network&confidence=95&ignoreDisruption=1&ignoreMissing=0&includeVariant=Architecture%3Aamd64&includeVariant=FeatureSet%3Adefault&includeVariant=Installer%3Aipi&includeVariant=Installer%3Aupi&includeVariant=Owner%3Aeng&includeVariant=Platform%3Aaws&includeVariant=Platform%3Aazure&includeVariant=Platform%3Agcp&includeVariant=Platform%3Ametal&includeVariant=Platform%3Avsphere&includeVariant=Topology%3Aha&minFail=3&pity=5&regressedModal=1&sampleEndTime=2024-08-02%2023%3A59%3A59&samplePRNumber=&samplePROrg=&samplePRRepo=&sampleRelease=4.17&sampleStartTime=2024-07-26%2000%3A00%3A00)

image

image

### CODE REVIEW

**Comment by stbenjam** [comment]
- I like the drill down a lot.  Very easy to navigate. It wasn't immediately obvious to me to click on one of the triaged incidents, though. On most tables in Sippy, actions tend to be a button on the rightmost column.   Even if clicking anywhere on the row does it, it might be more obvious if there were buttons to "View Tests", and "View Job Runs", similar to the jobs table

- I'm always a little concerned about the maintenance overhead in new JS dependencies.  Can we make do without react-split-pane? You should be able to reproduce it with Material UI's `<Grid>`.  It was last updated 4 years ago which is concerning. eventemitter3 is less concerning given its wide use.

- We try as much as possible that if I share a link from a page, the recipient of the link gets the same exact view.  Could we move the selected incident and test to query parameters?

- Is it possible to hide the right and bottom panels until they need to be displayed? That'd direct the users focus to know which panel they need to pay attention to

- Do we need to show the job run ID's, or could we opt for red `F`'s like we have on the test details page?

**Comment by neisw** [comment]
- Button for selection should be doable
- Yeah, I'm unsure on the usefulness of the splitter windows and open to removing them.
- Reflecting the state in the URL and updating it automatically would be nice
- At one point I thought about a vertical stack of windows or overlaying pop up windows ontop of each other.  If we are going to toggle visibility based on selection would something like that be more desireable?
- I feel like there is value to the run ID's when it comes time to use this view for adding / updating triage records.  We only show failures in this view and the `F`'s make it hard to tell what you have looked at already (I would really like the link to indicate if we had visited it already as well...)

**Comment by stbenjam** [comment]
> * Button for selection should be doable
> * Yeah, I'm unsure on the usefulness of the splitter windows and open to removing them.
> * Reflecting the state in the URL and updating it automatically would be nice
> * At one point I thought about a vertical stack of windows or overlaying pop up windows ontop of each other.  If we are going to toggle visibility based on selection would something like that be more desireable?

That would work too.  It looks like MUI handles nested modals: https://mui.com/material-ui/react-modal/#nested-modal

Either way works, I'm not opposed to the splitter view, just that older dependency.  It might not cause a problem but I've been burned so many times wrestling with npm deps when trying to fix a CVE that I try to avoid adding new ones.

> * I feel like there is value to the run ID's when it comes time to use this view for adding / updating triage records.  We only show failures in this view and the `F`'s make it hard to tell what you have looked at already (I would really like the link to indicate if we had visited it already as well...)

We might be overriding the style somewhere, but you could change `a:visited` style  for those links

**Comment by stbenjam** [comment]
This version looks really good.  I like the idea of a test details-like page for the regressions, but I think this could merge as is if you want it live now.

**Comment by neisw** [comment]
Thanks!  Seems worth getting this in and then continuing to build it out.

**Pull request merged**
