### PR TITLE
e2e interval charts: limit tooltip width to first word width

### PR DESCRIPTION
**Pull request by vrutkovs**
Two quality-of-life improvements for e2e charts:

*  wrap tooltips in e2e chart to make sure that tooltips don't overflow X when a long label is used.
*  copy segment label contents to clipboard when its clicked

Ref: https://github.com/openshift/origin/pull/27965

### CODE REVIEW

**Comment by dgoodwin** [comment]
Probably was not fair of me to suggest you add this here Vadim, something looks broken and it would require a little knowledge on standing up sippy db, api, and node UI. We can pickup this PR from here, thank you for trying, it will help us get it in regardless.

**Comment by vrutkovs** [comment]
Sure, I don't mind leaving it under review for some time

**Comment by stbenjam** [comment]
I think the e2e test was just hitting search.ci problems, I tested this locally and works for me, but I'm curious if @dgoodwin saw some other problem

/test e2e

**Comment by dgoodwin** [comment]
No I didn't dig into the failures, mistakenly assumed it was the PR.

**Pull request closed without merging**
