### PR TITLE
Show 14-day job run history widget on release overview page

### PR DESCRIPTION
**Pull request by stbenjam**
[TRT-259](https://issues.redhat.com//browse/TRT-259)

This changes the release overview page to show the 14-day job run
history.  The 24-hour view is still visibile by clicking through
to the job analysis page, and selecting "View by Hour."

This also fixes the test view to show per-day and per-hour views.

image

### CODE REVIEW

**Comment by stbenjam** [comment]
/assign @dgoodwin 

Could you take a look at this one too? Thanks!

**Comment by stbenjam** [comment]
I had to rename my migration :-\ https://github.com/openshift/sippy/pull/452 was newer

**Comment by dgoodwin** [comment]
We gotta figure that out, that's totally screwed up.

/lgtm

**Pull request merged**
