### PR TITLE
Add a new 'assisted' variant

### PR DESCRIPTION
**Pull request by omertuc**
See commit message

### CODE REVIEW

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by omertuc** [comment]
We've decided to look for alternative ways to get Sippy to work as we expect, closing this for now

**Comment by stbenjam** [comment]
> We've decided to look for alternative ways to get Sippy to work as we expect, closing this for now

Is there any reason you don't want a variant for assisted? This change looked correct to me.

**Comment by omertuc** [comment]
> > We've decided to look for alternative ways to get Sippy to work as we expect, closing this for now
> 
> Is there any reason you don't want a variant for assisted? This change looked correct to me.

It's not that I don't want, it's just that the original goal was to get *all* assisted jobs into sippy (so we could get a nice UI / overview) but we later realized sippy only consumes informing testgrids and 95% of our jobs are not informing, so we decided we should probably create our own instance of Sippy pointing at non-informing test grids for assisted.

The change still makes sense though, assisted is a better variant than "metal-assisted", so if it's fine by you we can merge this

**Comment by dgoodwin** [comment]
Sippy's about to change pretty dramatically so I would not recommend setting up a new instance just now, but what kind of data are we missing? I thought we got all periodics.

**Comment by omertuc** [comment]
>Sippy's about to change pretty dramatically so I would not recommend setting up a new instance just now, 

Thanks for the heads up. 

> but what kind of data are we missing? I thought we got all periodics.

We have a lot of assisted related periodic jobs that are not part of "release-controller", i.e. non-informing periodics. We want to track them with sippy. You can see them at `#assisted-deployment-ci`, but one arbitrary example `periodic-ci-openshift-assisted-service-master-e2e-metal-assisted-operator-ztp-periodic-upgrade`

**Comment by dgoodwin** [comment]
Ok let me check with the team this morning, but I think we can probably find a way to get these into sippy for you.

**Pull request merged**
